services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=trace
      - DB_PASSWORD=trace_secret
      - DB_NAME=trace_db
      - DB_PORT=5432
    depends_on:
      - db
    restart: on-failure

  web:
    build: ./web
    ports:
      - "3000:80" # На хосте приложение будет доступно на localhost:3000
    depends_on:
      - app
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=trace
      - POSTGRES_PASSWORD=trace_secret
      - POSTGRES_DB=trace_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: